export const categoryConstants = {
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

    SAVE_QUESTION_SUCCESS: 'SAVE_QUESTION_SUCCESS',
    SAVE_QUESTION_FAILURE: 'SAVE_QUESTION_FAILURE',
};
