export const categoryConstants = {
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

    SAVE_QUESTION_SUCCESS: 'SAVE_QUESTION_SUCCESS',
    SAVE_QUESTION_FAILURE: 'SAVE_QUESTION_FAILURE',

    GET_QUESTION_LIST_SUCCESS: 'GET_QUESTION_LIST_SUCCESS',
    GET_QUESTION_LIST_FAILURE: 'GET_QUESTION_LIST_FAILURE',

    SAVE_ANSWER_SUCCESS: 'SAVE_ANSWER_SUCCESS',
    SAVE_ANSWER_FAILURE: 'SAVE_ANSWER_FAILURE',

    GET_ANSWER_LIST_SUCCESS: 'GET_ANSWER_LIST_SUCCESS',
    GET_ANSWER_LIST_FAILURE: 'GET_ANSWER_LIST_FAILURE'
};
